---
- name: Update local apt cache
  apt:
    update_cache: yes
- name: Ensure Apache is at the latest version
  apt:
    name: apache2
    state: latest
    update_cache: yes
- name: echo a simple webpage
  shell: echo "<h1>Super Awesome Webpage</h1>" > /var/www/html/index.html
- name: Make sure Apache is running
  systemd:
    state: started
    name: apache2