---
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
- name: Ensure Apache is at the latest version
  apt:
    name: apache2
    state: latest
    update_cache: yes
- name: Make sure Apache is running
  systemd:
    state: started
    name: apache2